### ISSUE TITLE
Feedback on tidyup 004: Governance model

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidyups#16]
We’d love to get your thoughts on https://github.com/tidyverse/tidyups/blob/main/004-governance.md, a proposal to define a standard governance model across the tidyverse. Hopefully there are no major surprises here; this is the model we've implicitly been operating under for a while. 

Please feel free to contribute however you feel comfortable — you're welcome to make small fixes via PR, comment here, or open bigger discussion topics in an new issue. If there are things you’d prefer to discuss in private, please feel free to email me.  I’ll plan to close the discussion on **August 18**, so we can review and make adjustments as needed.

@tidyverse/authors

**Comment by mgirlich** [comment]
Looks good to me. I like the idea of combining rough consensus with the benevolent dictator. What you've written also feels very much like what I've seen and experienced so far, well done!

**Comment by hadley** [comment]
Thanks @mgirlich. Any other @tidyverse/authors let us know if you have any comments before Aug 18th 😄

**Comment by yutannihilation** [comment]
Sorry for the late reply. Looks good. One thing I wanted to know before becoming ggplot2 author is the relationship with tidyverse org, so it might be nice to include this

> Are a member of the “authors” team of the tidyverse organisation, so they are publicly acknowledged and can easily be cc’d in tidyverse-wide discussions.

in the invitation email somehow.

I also want to know how authors should behave on other tidyverse repos. While authors are typically responsible only for several packages, they are recognized as the members of tidyverse (as GitHub actually labels "Member" on their comments) to those who are not familiar with the governance structure. But, this might be a bit different topic.

**Comment by hadley** [comment]
@yutannihilation Good point, I'll definitely update the invite email. Good spotting with the member badge; I'd never noticed it before. I'm not sure what to do about it. Maybe just point out to potential authors that you'll be representing the tidyverse org when interacting in other repos, so particularly important to be friendly and welcoming?

**Comment by yutannihilation** [comment]
Sounds good!
